//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashBill
    {
        public CashBill()
        {
            this.CashBillDetails = new HashSet<CashBillDetail>();
        }
    
        public int ID { get; set; }
        public string BillCode { get; set; }
        public string CustomerName { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public System.DateTime Date { get; set; }
        public string Shipper { get; set; }
        public string Note { get; set; }
        public int GrandTotal { get; set; }
    
        public virtual ICollection<CashBillDetail> CashBillDetails { get; set; }
    }
}
